### ISSUE TITLE
Does this library supports KSP?

### ISSUE THREAD

**Issue by mochadwi** [IVIanuu/injekt#358]
Or did you mean using Kotlin Compiler Plugins is has same approach with KSP to generate processor so it's not using neither KAPT nor KSP?

**Comment by IVIanuu** [comment]
I use this library in my projects together with KAPT so i guess it should also work with KSP

**Comment by mochadwi** [comment]
This library was platform agnostic right (not coupled with android) ? So the KMM is supported

**Comment by IVIanuu** [comment]
This library could be KMM but isn't at the moment.
