### ISSUE TITLE
Use from downstream libraries

### ISSUE THREAD

**Issue by sgammon** [IVIanuu/injekt#509]
I really like how this package is set up. I am thinking of using it in a downstream library. Before I do, though, I just had a few questions :)

1) Licensing? has this project determined a license yet?
2) Republishing? since this plugin is experimental, would the authors be okay with us publishing our own artifacts and keeping them in sync with our own?
3) Multiplatform? Does it support it? Just curious

Thank you in advance and we are excited to find this library

**Comment by IVIanuu** [comment]
Sorry for the late response.

You could use this library if you get it to run properly, it's highly experimental and it has some issues with ide support and incremental compilation for example.

1. This project is using Apache 2.0 licence.
2. Yes you could republish it.
3. It does support JVM and JS targets but I haven't implemented native support.

**Comment by sgammon** [comment]
@IVIanuu understood, thank you for the advice. for now i'm using Micronaut's DI container on JVM, so i'll follow this project and jump in when it supports other platforms :) thank you for your hard work in the Kotlin universe
